server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka7002
  client:
    fetch-registry: false         # 表示自己就是注册中心,就是维护服务实例的
    register-with-eureka: false   # 自己不注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
