server:
  port: 8820

spring:
  application:
    name: cloud-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql 驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      max-active: 30
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seata.entity

